version: "3"
services:
  elasticsearch:
    image: elasticsearch-river-couchdb
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/elasticsearch:/usr/share/elasticsearch/data/elasticsearch

  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    volumes:
      - ./couchdb/couchdb:/opt/couchdb/data
